eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  server:
    renewal-percent-threshold: 0.85
spring:
  application:
    name: eureka
server:
  port: 8761